[crates]
inferno = "0.12.2"
spider_cli = "2.36.84"

[options]
workspace_path = "./warehousify/"
verifying_key = "RWShENTklmu4qg2Xk0yffAuCkzZv74VieiE8UST9SLnU/AQloFfe/OuY"
signing_key = "RWQAAEIyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoRDU5JZruKooeVuIuT7Mme2mPxByDCwSOU42VmWePJ8V92r9D4va8w2Xk0yffAuCkzZv74VieiE8UST9SLnU/AQloFfe/OuYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

[dependencies]
cargo-auditable = { enabled = true, version = "0.6.0" }
nil = { enabled = true, version = "0.0.0" }
cargo-clicker = { enabled = true, version = "0.1.0" }
doesntexist = { enabled = false, version = "^0.1.1" }
moredoesntexist = { enabled = false, version = "=1.0.100" }
somedoesntexist = { enabled = false, version = "1.0" }
cratesdoesntexist = { enabled = false, version = "1" }
guhdoesntexist = { enabled = false, version = "*" }
