[crates]
exa = "0.10.1"
cargo-binstall = "1.12.5"

[options]
autodelete_sources = false
workspace_path = "./warehousify/"
verifying_key = "RWQiiqKPv2GEs2Z3jnn2iqA9/E7Mo5/YNvp2pJ/fxylm2BumXygXJMhx"
signing_key = """untrusted comment: minisign encrypted secret key
RWRTY0IydA2kJs9dAkiEceVoA5CFaV1prCDCqOawZZ5JRyZ8zsMAAAACAAAAAAAAAEAAAAAA9hLIknec811yQ+a9d7Tv74qax3NXQwgxtmLdKeiK1MntMIecC9Vu0AZd0Kx4VOgSFlXtegajRL2XAvESaML2OrgdyqJ8sFm2SXktaZsUExJUKVCFBREgl8F8z/GLA8fJnYCYCik56j8="""

[dependencies]
cargo-auditable = { enabled = true, version = "0.6.0" }
